# Patch for argocd-cm to enable GitHub SSO via bundled Dex.
# Replace GITHUB_CLIENT_ID with your OAuth app Client ID and GITHUB_ORG with your GitHub org name.
# Only members of that org can log in. Store the client secret in argocd-secret (see GITHUB-SSO.md).
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Argo CD base URL (must match how you reach the UI; used for OAuth callback)
  url: https://argocd-server-lb.argocd.local/
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: Ov23liVUCcnUqoN9dooy
        clientSecret: $dex.github.clientSecret
        orgs:
        - name: shields-farm
